language: node_js

addons:
  chrome: stable

cache:
  yarn: true

sudo: required
dist: trusty

jobs:
  fail_fast: true
  include:
    # runs linting and tests with current locked deps

    - stage: 'CommitLint'
      name: 'Conventional Commits'
      node_js: '10'
      script:
        - commitlint-travis

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Tests'
      node_js: '10'
    - node_js: '8'
    - node_js: 'stable'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive
before_script:
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - sudo chown root /opt/google/chrome/chrome-sandbox
script:
  - yarn test:ci && yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
